name: Fetch Runs

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=3" > runs.json
          curl --upload-file runs.json https://transfer.sh/runs_918237.json || true
